### ISSUE TITLE
it is possible to export the client as c# or vb.net shellcode? 

### ISSUE THREAD

**Issue by illusion-linux** [quasar/QuasarRAT#372]
Hello
it is possible to export the client as c# or vb.net shellcode? 
i want to include the client into another c# program i made
how to achieve this ?

**Comment by MaxXor** [comment]
No, what you can do is build a client and put it in your resources. At runtime you can extract it from the resources and run it.

**Comment by illusion-linux** [comment]
OK 
but this will be not be FUD only if it was executed in memory so i can by-bass AV's 
i m 0 knowledge in programming but i have some skills in scripting in bash and php
my idea is simple can i at least build the client from source not from the binary builder (Quasar.exe) 
not like a binder but execute my client in memory

**Comment by yankejustin** [comment]
@illusion-linux if you have no programming knowledge, explaining the process would be a,bit pointless because it is not that simple. It is important to have some programming knowledge to know exactly what is going on and how to do it yourself. Otherwise, someone would essentially hold your hand the whole way through the process. :(

**Comment by yankejustin** [comment]
@illusion-linux I'd suggest taking the time know how to use a language well so these concepts explained to you will be concepts that you can actually make use of.

**Comment by MaxXor** [comment]
You can build the client from source (debug configuration) and edit your Settings here.
Anyways discussing of bypassing AVs is not allowed [here](https://github.com/quasar/QuasarRAT/blob/master/Client/Config/Settings.cs#L13).
