### ISSUE TITLE
Use the Github milstone feature more

### ISSUE THREAD

**Issue by webiummedia** [quasar/QuasarRAT#391]
Github has a great milestone feature where the work in progress can be seen. When a milestone is finished a new release could be made. Breaking down all the user enhancement asked as well as the current development choices to small milestone goals would let us (poor users lol) know on what features you are working on and what will be next. Also, milestones can be attributed to someone so if more then one dev drops in they can work on different approved features in a more organized way. When enhancement tag is added, it should be added in the milestone. Right now i only see 2 in there.

**Comment by yankejustin** [comment]
A little bit rude to open up a bunch of issues without grouping the ones relating to the same enhancement (example: file transfer enhancements split over many different issues) and then saying to use milestones for the small things. Generally, milestones are easy to use for things related to the next releases (some minor, but others for the next major release).
Anyways, I like your suggestions and ideas, but for ones more for discussion on how to manage the repository, it is best to use Gitter because there is generally quite a lot that goes into managing projects.
Also, Github issues are unfortunately not good for suggestions such as this: they are really black and white when it comes to the outcome instead of promoting debate like Gitter does.
Bring it up with MaxXor is Gitter. My opinion is that it is used for things that are major such as related changes to make before a new release or a very large addition to Quasar.

**Comment by yankejustin** [comment]
I'd also like to point out that nearly all of the issues opened currently are enhancements. It is especially hard to group every one of the ~30 enhancement suggestions: especially when there aren't many of us actively developing (and how busy we have ended up getting this past month). :)
It is pretty much a thing to where a developer can cherry pick interesting enhancements and implement them if desired.

**Comment by webiummedia** [comment]
I was not being rude by opening a bunch of threads. In fact I was just doing exactly what you asked for in #366 "@webiummedia Just make sure to have a separate issue for each suggestion or problem. "

All i want is to help how I can. And that is to test and point out what i find. I am a senior Web Dev in real life. We use Github a lot for major projects so I was just trying to help. Normally I would of done only one big thread for all my suggestions but as per your own request i ended up doing one per thread.

In any case, we use the milestones a lot and each milestones is assigned when worked on and closed when finished. For example, all the issues related to the file manager should be joined into one milestone. So when a dev starts working on it he/she can address each one of them in one shot instead of having them open and everywhere. I don't want to sound rude, I was just suggesting to use the milestone in a more proactive way to help organize a little the place.

**Comment by yankejustin** [comment]
I meant that unrelated problems should be separated...
Also, I just wanted to point out that those of us that develop this program actively are on a chaotic schedule and unfortunately often end up working on this best by picking up wherever we can. :)

**Comment by yankejustin** [comment]
As for the milestones, I could make them whenever all of us devs figure out when we'll have times for releases of these features... And the accompanying release date to go with it.

**Comment by yankejustin** [comment]
I do see your perspective though. I was thinking about using milestones for releases, but it is interesting to use them for tracking many of the issues. I'll have to experiment some time and see which ends up working best.

**Comment by MaxXor** [comment]
@webiummedia thank you very much for all of your suggestions, I've read them all. I see how the milestone feature could be useful, but at the moment we are more or less 3 people developing this and releases are currently pushed out when I think it's stable and has some improvements over the past release. I need to get more used to the milestones.
