### ISSUE TITLE
Webcam Support

### ISSUE THREAD

**Issue by mendes12721** [quasar/QuasarRAT#404]
I'm not sure if here is the right place to put this but do you have planned a webcam support?

**Comment by KNEG** [comment]
I'm new to this rat. Still looking through the files and seeing how everything is put together. I'm going to commit a webcam feature and disabling devices and drivers on the victims computer. I suggest you learn how to because this seems like a group project and should commit to make it better. Pretty solid project so far though.

**Comment by mendes12721** [comment]
First off all I must congratulate you all coders and helpers because this is the only rat  working on Windows 10 with the Windows defender active... about the coding I do know how to code a little bit, but I have little to no time ... and this project deserves People with time to spare and invest on Quasar.

**Comment by MaxXor** [comment]
There is already an open issue on webcam support. Yes, we're gonna add this, but there is no ETA.
Thanks for your feedback!
