### ISSUE TITLE
Registry Editor doesn't work correctly on 64-bit systems

### ISSUE THREAD

**Issue by DragonzMaster** [quasar/QuasarRAT#425]
I tried to use registry editor in release config but it seems to be not working even when I run the client with admin privil. but when I tried it using debug config it works good.

**Comment by DragonzMaster** [comment]
ok, thanks in advance.

**Comment by DragonzMaster** [comment]
I forget to mention that when I tried to view values in HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run it get the values from the same key but Current user not local machine
so it need to be fixed too, and make it view the values from the correct key

**Comment by StingRaptor** [comment]
@DragonzMaster I have looked at the `HKEY_LOCAL_MACHINE` registry but can't seem to recreate the your error. However, I have found that the `RegistryEditor` only seems to work against the 64-bit registry (even if the Client is 32-bit).

**Comment by DragonzMaster** [comment]
What I mean that when I open 
 HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run 
it shows the values from
 HKEY_LOCAL_MACHINE\**WOWNode64**\SOFTWARE\Microsoft\Windows\CurrentVersion\Run

**Comment by StingRaptor** [comment]
Ok, seems that this is what I mentioned about the `RegistryEditor` only working against the 64-bit registry. In the future this should probably be extended to make it possible to edit both 64-bit and 32-bit registry values/keys, however I will put this on hold and handle it in later updates.

**Comment by MaxXor** [comment]
@StingRaptor The client registryeditor is working partially on 64-bit systems. As @DragonzMaster said. For example when you try to access keys from `HKEY_LOCAL_MACHINE\SOFTWARE\*` it will give you instead the keys from `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\*` on 64-bit systems.
Same for `HKEY_CURRENT_USER\Software\*`.

On 32-bit systems it's working correctly.

We will need to add the enum `RegistryView` (https://msdn.microsoft.com/en-us/library/microsoft.win32.registryview(v=vs.100).aspx) to the code and use `Registry64`. It _should_ be safe to use this because of this:

> If you request a 64-bit view on a 32-bit operating system, the returned keys will be in the 32-bit view.

Sources:
[Wikipedia - WoW64 (Windows 32-bit on Windows 64-bit)](https://en.wikipedia.org/wiki/WoW64)
[MSDN - RegistryView Enum](https://msdn.microsoft.com/en-us/library/microsoft.win32.registryview(v=vs.100).aspx#Anchor_1)

**Comment by DragonzMaster** [comment]
@MaxXor - @StingRaptor, You can give this a look :
(*) https://regexplore.codeplex.com
this project works fine for me, It might help you. :smile:

**Comment by MaxXor** [comment]
.... it doesn't need changes as it's compiled for `AnyCPU`, ours x86. That's the difference why it's working.

**Comment by DragonzMaster** [comment]
So what is preventing us to compile Quasar client for AnyCPU ??

**Comment by MaxXor** [comment]
The password recovery. (see: https://github.com/quasar/QuasarRAT/issues/352) It was solution 3.

**Comment by StingRaptor** [comment]
Thank you for the help, @MaxXor  and @DragonzMaster. I have now made the needed changes, and it seems that  the RegistryEditor is working and displaying the correct keys in a 64-bit system. :smile:

**Comment by DragonzMaster** [comment]
Thank you for you efforts, @StingRaptor .I've tested the client from your fork and it seems to be fixed. The project which I mentioned before can help you to get Default values and allow you to search the registry.

**Comment by MaxXor** [comment]
@StingRaptor Yes please adjust the form.

**Comment by StingRaptor** [comment]
@DragonzMaster @MaxXor Ok, this is a quick fix. However what is a reasonable size?

**Comment by MaxXor** [comment]
Yes.

**Comment by StingRaptor** [comment]
@DragonzMaster I will look at the link you provided when I have more time on my hands, Thank you. :smile:

Title and form size fixed in: 6492b2734d533690d7c93b312e904d79e642e401
