### ISSUE TITLE
Cut out UI on high DPI display Win10

### ISSUE THREAD

**Issue by ViRb3** [quasar/QuasarRAT#474]
![Image](https://i.imgur.com/UGmq6dF.png)

This is the case everywhere in Quasar RAT.
125% scaling, disabling DPI scaling via Compatibility tab has no effect.

**Comment by caesay** [comment]
I'm on windows 10 at the latest source with a high DPI display and can't reproduce this issue. Fixed?

**Comment by MaxXor** [comment]
@caesay I didn't change anything yet. Strange. Do you use Quasar from the latest commit?
@ViRb3 Do you use Quasar from the latest commit?

**Comment by caesay** [comment]
@MaxXor Yeah, I just cloned it. I'm on 630f791. I've dealt with a lot of DPI issues in my projects and I thought this issue looked strange. On high DPI usually the application is either tiny because its not scaled at all, or blurry because the application was not DPI aware and windows does a raster scaling on it - I've never seen the window stay small and the content get bigger. It could be a font size thing, I'll try and dig a bit more tomorrow.

**Comment by MaxXor** [comment]
@caesay So how does it look on your screen? Can you do a screenshot if possible? Is it tiny or blurry?

**Comment by caesay** [comment]
@MaxXor You've correctly left out the dpi awareness tag from the manifest, so its currently being scaled by windows. It doesn't look bad, though. Unless you're looking at it on a 4K screen you probably won't be overly bothered by the windows scaling / blurriness.

Personally I don't think that this is the type of application that needs crisp visuals, and in the case that it is I would *definitely* recommend WPF. That being said, if you're curious you can look into the Form properties `AutoScaleDimensions` and `AutoScaleMode`. When a WinForms application is set as DPI-Aware I believe .Net takes over and those are the values that are used to calculate the scaling.

Unfortunately, neither WPF nor WinForms properly support varied monitor-independent DPI settings, so if you set your application to DPI-Aware without handling this yourself, your scaling will be off when moving your window across monitor boundaries with different DPI's. Right now, windows visualizes this for you and i'd recommend you leave it that way.

The problem that i think is causing this is what i call "XP Scaling", which appropriately dates back to XP, It basically scales only system fonts and some system UI elements like titlebars, scrollbars, etc. leaving the rest of the interface intact. So when you move your application to a higher DPI environment, the only difference is that the text suddenly gets bigger. This sounds like the issue, so its probably a setting on @ViRb3 's computer to utilize this scaling method instead of DPI scaling.

**Comment by ViRb3** [comment]
Yes, indeed, I am using Windows 8 DPI scaling instead of Windows 10 since many of my programs don't support it and get blurred. Any chance to support both scaling methods?

**Comment by MaxXor** [comment]
Thanks for all your input @ViRb3 and @caesay! :+1:  I think it's fixed now to be correctly DPI aware, I've tested it in VM with DPI set to 125%.
Can you confirm it's working correctly with the latest commit https://github.com/quasar/QuasarRAT/commit/0d3a3e427d166d7f659858613705d725ec349b0e?
