### ISSUE TITLE
Still Working on Quasar?

### ISSUE THREAD

**Issue by ChainF** [quasar/QuasarRAT#553]
Are you still Updating Quasar?

**Comment by DragonzMaster** [comment]
He said that he will publish a roadmap but unfortunately he didn't and didn't even merge any PR.

**Comment by EnricoVogt** [comment]
Maybe he is busy at the moment....

**Comment by Sl0thzy** [comment]
I'd be willing to work on this if I get the time eventually and he is no longer active on Quasar.

**Comment by luckystr1keno7** [comment]
Someone should take over this project, it has come a long way and it's a pity to end this way...maybe he hoped to receive more donations to his BTC address after he released the new version but when that didn't happen he turned his attention to something else...he should at least merge the pull requests

**Comment by MaxXor** [comment]
I'm currently doing my M.Sc. degree in CS and have very little time for my projects (not only this). Please view this as a break for the development of Quasar, not the end.
@luckystr1keno7 I think someone read your message and donated $200, check out the donation address. Thanks to the anonymous donator! I can't merge all of the pull requests, some need to get rebased to the latest master branch and others are not well tested. I'll check them once I get more time.

**Comment by ChainF** [comment]
That's good to hear, wish you good luck with your M.Sc. degree :)

**Comment by DragonzMaster** [comment]
Oh, that's nice. Good luck with your M.Sc degree.
Hope you the best bro. ;)

**Comment by luckystr1keno7** [comment]
@MaxXor enjoy your tip, you've done a great job and you deserve it...my lucky guess is that, there is a lot more coming your way once you get some new updates rolling, just saying...:)

**Comment by yankejustin** [comment]
I used to contribute often but I now have a full-time job and some hobbies outside of programming. I will start working on this project once I build a nice gaming/programming-worthy computer, but I doubt I will be able to contribute until then.
The problem is that there are few developers and lots of different cool things that can be added (a complete re-write would be nice to a more-modular program, feature additions, performance improvements, reliability improvements, etc).

**Comment by Galaden** [comment]
> start working on this project once I build a nice gaming
heh ganing pc is priority?))

**Comment by yankejustin** [comment]
Gaining a pc is a priority - one that is strong enough to handle games will also be strong enough for me to do things I have been wanting to do with this program and some other programming projects. After I lost the computer I used to work on Quasar with I have slowed down on programming.
In any case, luckystr1keno7 seems to be helping push changes by paying for people to work on the project, and that is nice to see. It is appreciated since we all love this program. :)
