### ISSUE TITLE
Connection settings, how to use outside your network

### ISSUE THREAD

**Issue by BatLine** [quasar/QuasarRAT#653]
Hi, as the title says, i'm having some trouble with that, the only thing I tried was to use my own ip4 and run it and also localhost, but what do I have to type to acces the cleint on another pc? (on the same network and or on another wifi network)??

**Comment by BackfireRAT** [comment]
Port forwarding and Firewall settings. Make a firewall rule that allows data inbound and outbound from the port you want. Next, set up your router to forward any connections on that port to your ipv4 address. You'll also need a NO-IP/DynDNS or a VPN because ISPs can change your IP and the connections will go somewhere else. Just search "NO-IP" and "Port Forward" or "How to setup RAT"
