### ISSUE TITLE
Some Pull Requests

### ISSUE THREAD

**Issue by XYDsoft** [quasar/QuasarRAT#694]
There are many good "Pull requests",I hope the author can be integrated together. After all, the last update of QuasarRAT has been in the past 2 years.  We urgently hope that the author will update this project.  But every time I see 2 years ago, I believe many people are willing to sponsor this project.

**Comment by MaxXor** [comment]
No, this will not become a commercial software, but I'm thinking about offering enterprise support for those who use Quasar in business. Regarding the open PRs, most of them are huge changes to Quasar and not easy to review (due to not following the [contributing guidelines](https://github.com/quasar/QuasarRAT/blob/master/CONTRIBUTING.md)), also I can't add new features while I'm working on refactoring Quasar according to the roadmap on the `dev` branch. This would get a huge mess.
