### ISSUE TITLE
Releases page shows "Dangerous" in chrome

### ISSUE THREAD

**Issue by notoDevo** [quasar/QuasarRAT#769]
Hello, 

I am quite new to quasar RAT , basically was looking for a RAT for legitimate purposes of remotely handling machines within the organization. When I go to the releases page google chrome raises a "Dangerous" flag, above it. Just wanted to let you know so you guys can see about that.

Might be a stupid question but: Is it safe to download quasar RAT?

![Capture-quasar](https://user-images.githubusercontent.com/24829396/60599975-08482580-9db8-11e9-852e-496f727f2738.JPG)

**Comment by yankejustin** [comment]
That's pretty funny. I actually don't necessarily disagree with Chrome I suppose. These kinds of checks on Windows and Google Chrome is in effort to prevent people from mistakenly doing something that could compromise their safety.
The term "harmful programs" is subjective:
To a novice computer user, this program isn't going to be that helpful to them in its current state. And without proper knowledge on configuring this program, they're going to have a bad time.
To a computer user that understands what a remote administration tool is and that decides to learn how to use it (reading through the closed tickets and such and seeing common issues/documentation/responses), this tool is extremely helpful in both a personal and business setting.

So in a technical sense, most antiviruses will detect this program as "malware" simply because it wants to make sure you know what you're doing since this tool is pretty powerful. Computer management software gives an enormous amount of control over another machine by design.

That being said, I don't understand the last question... The downloadable files in this repository are built directly from the source code.

Hope that clears things up a bit.

**Comment by yankejustin** [comment]
If you'd like to download the files and you understand the purpose of this software, you can click on the **details** of that page that Google Chrome is redirecting you to, and you can proceed to the download page as intended.

You will also likely have to add an exception to your antivirus software.
